# Generated by Django 5.2.8 on 2025-11-13 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "userID",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("firstname", models.CharField(max_length=100)),
                ("lastname", models.CharField(max_length=100)),
                ("google_account", models.CharField(max_length=255)),
                ("first_auth_ts", models.DateTimeField(auto_now_add=True)),
                ("last_auth_ts", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "User Detail",
                "verbose_name_plural": "User Details",
                "db_table": "user_details",
            },
        ),
    ]
